DreamCatcher/src/DreamCatcher.Web/Controllers/DreamController.cs
using DreamCatcher.Domain.DreamAgg;
using DreamCatcher.Domain.DreamAgg.Contracts;
using DreamCatcher.Domain.SharedKernel.Helpers;
using DreamCatcher.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DreamCatcher.Web.Controllers
{

    [AllowAnonymous]
    public class DreamController : Controller
    {
        private readonly IDreamService _dreamService;

        public DreamController(IDreamService dreamService)
        {
            _dreamService = dreamService;
        }

        public ActionResult Index()
        {
            try
            {
                var user = SessionHelper.Getuser();
                if (null != user)
                {
                    var dreams = _dreamService.GetByUserId(user.Id);
                    return View(dreams);

                }

                return View(new List<Dream>());
            }
            catch (Exception)
            {

                throw;
            }

        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Edit = false;
            return PartialView("DreamModal", new DreamVIewModel() { RegisterDate = DateTime.Now });
        }

        [HttpPost]
        public ActionResult Create(DreamVIewModel dreamVIewModel)
        {
            try
            {
                _dreamService.Create(dreamVIewModel);
            }
            catch (Exception ex)
            {

                throw;
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            try
            {
                ViewBag.Edit = true;

                var dream = _dreamService.GetById(id);

                if(null != dream)
                    return PartialView("DreamModal", dream);

                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return View("Error");
                throw;
            }

        }


        [HttpPost]
        public ActionResult Edit(DreamVIewModel dreamVIewModel)
        {
            try
            {
                dreamVIewModel.IDUser = SessionHelper.Getuser().Id;
                _dreamService.Update(dreamVIewModel);
            }
            catch (Exception ex)
            {
                return View("Error");

                throw;
            }

            return RedirectToAction("Index");
        }
    }
}

DreamCatcher/src/DreamCatcher.Web/Controllers/DreamTaskController.cs
using DreamCatcher.Domain.DreamAgg.Contracts;
using DreamCatcher.Domain.SharedKernel.Helpers;
using DreamCatcher.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DreamCatcher.Web.Controllers
{
    [AllowAnonymous]
    public class DreamTaskController : Controller
    {

        private readonly IDreamTaskService _taskService;

        public DreamTaskController(IDreamTaskService taskService)
        {
            _taskService = taskService;
        }

        public ActionResult Index(Guid dreamId)
        {
            try
            {
                if (dreamId != Guid.Empty)
                {
                    ViewBag.IdDream = dreamId;

                    var tasks = _taskService.GetTasksByDreamId(dreamId);
                    return View(tasks);

                }

                return View(new List<DreamTaskViewModel>());
            }
            catch (Exception ex)
            {

                throw;
            }

        }

        [HttpGet]
        public ActionResult Create(Guid dreamId)
        {
            ViewBag.Edit = false;
            return PartialView("DreamTaskModal", new DreamTaskViewModel() { IdDream = dreamId });
        }

        [HttpPost]
        public ActionResult Create(DreamTaskViewModel taskViewModel)
        {
            try
            {
                _taskService.Create(taskViewModel);
            }
            catch (Exception ex)
            {

                throw;
            }

            return RedirectToAction("Index", new { dreamId = taskViewModel.IdDream });
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            try
            {
                ViewBag.Edit = true;

                var task = _taskService.GetTasksById(id);

                if (null != task)
                    return PartialView("DreamTaskModal", task);

                return RedirectToAction("Index", new { dreamId = task.IdDream });

            }
            catch (Exception ex)
            {
                return View("Error");
                throw;
            }

        }

        [HttpGet]
        public ActionResult MarkDone(Guid id)
        {
            try
            {
                if (Guid.Empty != id)
                    _taskService.MarkDone(id);

                var idDream = _taskService.GetTasksById(id).IdDream;

                return RedirectToAction("Index", new { dreamId = idDream });


            }
            catch (Exception ex)
            {
                return View("Error");
                throw;
            }

        }

        [HttpPost]
        public ActionResult Edit(DreamTaskViewModel DreamTaskViewModel)
        {
            try
            {
                _taskService.Update(DreamTaskViewModel);
            }
            catch (Exception ex)
            {
                return View("Error");

                throw;
            }

            return RedirectToAction("Index", new { dreamId = DreamTaskViewModel.IdDream });

        }

        public ActionResult Delete(Guid id)
        {
            Guid idDream;
            try
            {
                idDream = _taskService.GetTasksById(id).IdDream;
                _taskService.Delete(id);
            }
            catch (Exception ex)
            {

                throw;
            }

            return RedirectToAction("Index", new { dreamId = idDream });

        }
    }
}

DreamCatcher/src/DreamCatcher.Web/Controllers/HomeController.cs
using DreamCatcher.Domain.DreamAgg.Contracts;
using DreamCatcher.Domain.UserAgg.Contracts;
using DreamCatcher.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DreamCatcher.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDreamService _dreamService;
        private IUserService _userService;


        public HomeController(IDreamService dreamService)
        {
            _dreamService = dreamService;
        }
        public ActionResult Index()
        {
            return View("Index");
        }
    }
}

DreamCatcher/src/DreamCatcher.Web/Controllers/UserController.cs
using DreamCatcher.Domain.UserAgg.Contracts;
using DreamCatcher.Models.ViewModels;
using System;
using System.Web.Mvc;

namespace DreamCatcher.Web.Controllers
{
    [AllowAnonymous]
    public class UserController : Controller
    {
        private IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Create(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _userService.Create(userViewModel);
                    return RedirectToAction("Index", "Dream");

                }
                catch (Exception ex)
                {

                    throw;
                }
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login(string login, string password)
        {
            if (!String.IsNullOrEmpty(login) && !String.IsNullOrEmpty(password))
            {
                try
                {
                    var success = _userService.DoLogin(login, password);

                    if (success)
                    {
                        return RedirectToAction("Index", "Dream");
                    }
                }
                catch (Exception ex)
                {

                    throw;
                }
            }

            return RedirectToAction("Index", "Home");

        }
    }
}

DreamCatcher/src/DreamCatcher.Web/Views/Dream/Create.cshtml
@model DreamCatcher.Models.ViewModels.DreamVIewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DreamVIewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DreamCatcher/src/DreamCatcher.Web/Views/Dream/DreamModal.cshtml
@model DreamCatcher.Models.ViewModels.DreamVIewModel

@{
    ViewBag.Title = "DreamModal";

    Layout = null;

    bool Edit = ViewBag.Edit;
    var action = Edit ? "Edit" : "Create";
}

<div class="modal-dialog">
    <div class="modal-content">
        @using (Html.BeginForm(action, "Dream", FormMethod.Post))
        {
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">
                    Discussão
                </h4>
            </div>

            @Html.AntiForgeryToken()

            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @Html.LabelFor(model => model.RegisterDate, new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @*@{ Model.RegisterDate = Model.RegisterDate == null || Model.RegisterDate == DateTime.MinValue
                                ? DateTime.Now : Model.RegisterDate;}*@
                            @{ if (Model == null)
                                {
                                    @*@Html.TextBoxFor(model=> DateTime.Now.ToString("dd/MM/yyyy"), new { @class = "form-control", @readonly = "readonly" })*@
                                }
                                else
                                {
                                    @Html.TextBoxFor(model => model.RegisterDate, new { @class = "form-control", @readonly = "readonly" })
                                }
                            }

                            @Html.ValidationMessageFor(model => model.RegisterDate)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Title)
                        </div>
                    </div>

                    @Html.HiddenFor(x => x.Id)

                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
            </div>
        }
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -

DreamCatcher/src/DreamCatcher.Web/Views/Dream/Dreams.cshtml
@model DreamCatcher.Domain.DreamAgg.Dream

@{
    ViewBag.Title = "Dreams";
}

<h2>Dreams</h2>

<div>
    <h4>Dream</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDUser)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DreamCatcher/src/DreamCatcher.Web/Views/Dream/Index.cshtml
@model IEnumerable<DreamCatcher.Models.ViewModels.DreamVIewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Objetivos</h2>

<p>
    <button id="#nova" class="btn btn-info " type="button" onclick="getModal()">
        Criar Objetivo
    </button>
</p>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegisterDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegisterDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User)
            </td>
            <td>
                <button type="button" class="btn btn-info" onclick="getEditModal('@item.Id')">
                    Editar
                </button>
                <a class="btn btn-danger"
                   href="@Url.Action("Delete", "Dream", new { id = item.Id })">
                    Apagar
                </a>
                <a class="btn btn-danger"
                   href="@Url.Action("Delete", "Dream", new { id = item.Id })">
                    Apagar
                </a>

                @*@Html.ActionLink("Editar", "Edit", new { id = item.Id }) |*@
             @*   @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |*@
                @*@Html.ActionLink("Apagar", "Delete", new { id = item.Id })*@
            </td>
        </tr>
    }

</table>

<div class="modal" id="modal">

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script>
    function getModal() {
        $("#modal").load('@Url.Action("Create", "Dream")', () => {
            $("#modal").modal();
        });
    }

    function getEditModal(idDream) {
        $("#modal").load('Dream/Edit/' + idDream, () => {
            $("#modal").modal();
        });
    }

</script>

DreamCatcher/src/DreamCatcher.Web/Views/DreamTask/DreamTaskModal.cshtml
@model DreamCatcher.Models.ViewModels.DreamTaskViewModel

@{
    ViewBag.Title = "DreamTaskTaskModal";

    Layout = null;

    bool Edit = ViewBag.Edit;
    var action = Edit ? "Edit" : "Create";
}

<div class="modal-dialog">
    <div class="modal-content">
        @using (Html.BeginForm(action, "DreamTask", FormMethod.Post))
        {
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">
                    Discussão
                </h4>
            </div>

            @Html.AntiForgeryToken()

            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    @*<div class="form-group">
                        @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                          
                            @{ if (Model == null)
                                {
                                }
                                else
                                {
                                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @readonly = "readonly" })
                                }
                            }

                            @Html.ValidationMessageFor(model => model.Title)
                        </div>
                    </div>*@
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Title)
                        </div>
                    </div>

                    @Html.HiddenFor(x => x.Id)
                    @Html.HiddenFor(x => x.IdDream)

                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
            </div>
        }
    </div><!-- /.modal-content -->
</div>
<!-- /.modal-dialog -

DreamCatcher/src/DreamCatcher.Web/Views/DreamTask/Index.cshtml
@model IEnumerable<DreamCatcher.Models.ViewModels.DreamTaskViewModel>

@{
    ViewBag.Title = "Index";
    Guid idDream = ViewBag.IdDream;
}

<p>
    <button id="#nova" class="btn btn-info " type="button" onclick="getModal()">
        Adicionar Tarefa
    </button>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDone)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDone)
            </td>
            <td>

                @{
                    if (!item.IsDone)
                    {
                        <a class="btn btn-success"
                           href="@Url.Action("MarkDone", "DreamTask", new { id = item.Id })">
                            Fechar Tarefa
                        </a>

                        <button type="button" class="btn btn-warning" onclick="getEditModal('@item.Id')">
                            Editar
                        </button>
                    }
                }

                <a class="btn btn-danger"
                   href="@Url.Action("Delete", "DreamTask", new { id = item.Id })">
                    Apagar
                </a>
            </td>
        </tr>
    }

</table>


<div class="modal" id="modal">

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script>
    function getModal() {
        $("#modal").load('@Url.Action("Create", "DreamTask", new { dreamId =  idDream})', () => {
            $("#modal").modal();
        });
    }

    function getEditModal(idDream) {
        $("#modal").load('DreamTask/Edit/' + idDream, () => {
            $("#modal").modal();
        });
    }

</script>

DreamCatcher/src/DreamCatcher.Web/Views/Home/CreateUser.cshtml
@model DreamCatcher.Models.ViewModels.UserViewModel

@{
    ViewBag.Title = "CreateUser";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@*<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>*@

<h2>Criar Conta</h2>


@using (Html.BeginForm("Create", "User"))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(x=> x.Id);

    <div class="form-horizontal">
        @*<h4>UserViewModel</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmationPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmationPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmationPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

DreamCatcher/src/DreamCatcher.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-6">
        <img class="dream" src="~/Images/dreamImg.png"></img>
    </div>
    <div class="col-md-6">
        @Html.Partial("_AddEdtUser")
    </div>
</div>

DreamCatcher/src/DreamCatcher.Web/Views/Home/_AddEdtUser.cshtml
@model DreamCatcher.Models.ViewModels.UserViewModel

@{
    ViewBag.Title = "CreateUser";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@*<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>*@

<h2>Criar Conta</h2>


@using (Html.BeginForm("Create", "User"))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(x => x.Id);

    <div class="form-horizontal">
        @*<h4>UserViewModel</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmationPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmationPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmationPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

DreamCatcher/src/DreamCatcher.Web/Views/Home/_AddUser.cshtml
<div class="panel panel-primary">
    <div class="panel-heading">
        Cadastre-se
    </div>
    <div class="panel-body">
        <div class="form-group">
            <div class="form-group">
                <label for="email">Nome</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="form-group">
                <label for="senha">Senha</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="form-group">
                <label for="senhaConfirmar">Confirmar Senha</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="pull-right">
                <button type="submit" class="btn btn-color">Submit</button>
            </div>
        </div>
    </div>
</div>
<!--<div class="panel-footer right">

    <div class="text-right">
        <input type="submit" value="Save Usuário" class="btn btn-default" />
    </div>

</div>-->
</div>

DreamCatcher/src/DreamCatcher.Web/Views/Shared/_Layout.cshtml
@using DreamCatcher.Domain.SharedKernel.Helpers;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dream Catcher</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dream Catcher", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">

                    @{
                        if (!SessionHelper.UserLogged())
                        {
                            <li>
                                <form class="form-inline navbar-form navbar-left" role="search"
                                      method="post" action="@Url.Action("Login", "User")">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Usuario"
                                               name="login">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="Senha"
                                               name="password">
                                    </div>
                                    <button type="submit" class="btn btn-default">Entrar</button>
                                </form>
                            </li>

                        }
                        else
                        {
                            <li>@Html.ActionLink("Objetivos", "Index", "Dream")</li>
                            <li>@Html.ActionLink(@SessionHelper.Getuser().Name, "Index", "Dream")</li>

                        }
                    }
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dream Catcher</p>
        </footer>
    </div>
</body>
</html>